# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $183c383ff43d162a063761523ed2c94a29170ad0  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master